#!/usr/bin/env python3
"""
自动获取抖音 cookies
使用 Playwright 控制 Chrome 并导出 cookies
"""

import asyncio
import sys
import os

async def get_douyin_cookies():
    from playwright.async_api import async_playwright
    
    cookies_path = "/Volumes/movespace/workspace/Auto-home-sale-media-creator/apps/api/cookies/douyin.txt"
    
    async with async_playwright() as p:
        # 使用系统已安装的 Chrome
        browser = await p.chromium.launch(
            headless=False,
            executable_path='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
            args=['--disable-blink-features=AutomationControlled']
        )
        
        context = await browser.new_context(
            viewport={'width': 1280, 'height': 800}
        )
        
        page = await context.new_page()
        
        print("🚀 打开抖音网页版...")
        try:
            await page.goto("https://www.douyin.com/", timeout=60000)
        except:
            pass  # 超时也继续
        
        # 等待页面加载
        await asyncio.sleep(5)
        
        # 检查是否已登录
        try:
            # 寻找登录后的元素（头像）
            avatar = await page.wait_for_selector("[data-e2e='user-avatar']", timeout=5000)
            if avatar:
                print("✅ 检测到已登录状态")
            else:
                print("⚠️  未检测到登录状态，请手动登录")
                print("⏳ 等待60秒让你登录...")
                await asyncio.sleep(60)
        except:
            print("⚠️  未检测到登录状态，请手动登录")
            print("⏳ 等待60秒让你登录...")
            await asyncio.sleep(60)
        
        # 获取 cookies
        cookies = await context.cookies()
        
        # 格式化为 Netscape HTTP Cookie File 格式
        cookie_lines = [
            "# Netscape HTTP Cookie File",
            "# Generated by Playwright",
            "# Edit at your own risk",
            ""
        ]
        
        for cookie in cookies:
            domain = cookie['domain']
            flag = "TRUE" if domain.startswith('.') else "FALSE"
            path = cookie['path']
            secure = "TRUE" if cookie['secure'] else "FALSE"
            expiration = str(cookie.get('expires', 0))
            name = cookie['name']
            value = cookie['value']
            
            cookie_lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}")
        
        # 保存 cookies
        os.makedirs(os.path.dirname(cookies_path), exist_ok=True)
        with open(cookies_path, 'w') as f:
            f.write('\n'.join(cookie_lines))
        
        print(f"✅ Cookies 已保存到: {cookies_path}")
        print(f"📊 共 {len(cookies)} 个 cookies")
        
        # 检查是否包含关键 cookie
        cookie_names = [c['name'] for c in cookies]
        important = ['sessionid', 'sid_guard', 'ttwid', 'msToken']
        found = [n for n in important if n in cookie_names]
        print(f"🔑 关键 cookies: {found}")
        
        await browser.close()
        return True

if __name__ == "__main__":
    try:
        result = asyncio.run(get_douyin_cookies())
        sys.exit(0 if result else 1)
    except Exception as e:
        print(f"❌ 错误: {e}")
        sys.exit(1)
